apiVersion: v1
kind: Service
metadata:
  name: monsters-docs-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: monsters-docs
  ports:
    - name: http
      port: 80
      targetPort: 80
